name: beebuzz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0

  # Responsive UI
  sizer: ^2.0.15

  # Navigate Router
  go_router: ^13.2.2

  # State Management
  provider: ^6.1.2

  # Json Annotation
  json_annotation: ^4.8.1

  # APIs Call
  dio: ^5.4.2+1

  # APIs Function Generator
  retrofit: ^4.1.0

  # Cached Network Image
  cached_network_image: ^3.3.1

  # Singleton
  get_it: ^7.6.8

  # No-Sql Database
  hive: ^2.2.3

  # Local Notification
  flutter_local_notifications: ^17.0.0

  # Lite Database
  #sqflite: ^2.3.3

  # App Language
  flutter_localization: ^0.2.0

  # Pick Image
  image_picker: ^1.0.7

  # Flutter SVG
  flutter_svg: ^2.0.10+1

  # Chick Connection Status
  flutter_offline: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  rename:

flutter:


  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/bottom_bar/
    - assets/general/
    - assets/home/


  fonts:
    - family: inter-black
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
    - family: inter-bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: inter-extra-bold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
    - family: inter-extra-light
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: inter-light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: inter-medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: inter-regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: inter-semi-bold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: inter-thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
