// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSojdB_h9GJ3GXHNkVneACz1LuZTCFHX0',
    appId: '1:114708249147:web:72ef1f7196bf1125fa3a1e',
    messagingSenderId: '114708249147',
    projectId: 'beebuzz-dda69',
    authDomain: 'beebuzz-dda69.firebaseapp.com',
    storageBucket: 'beebuzz-dda69.appspot.com',
    measurementId: 'G-C3PTYEVYY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYfTSR4CDd11foswPPA_unUe_9fbuuMyg',
    appId: '1:114708249147:android:f9b40f6c4ce74ce7fa3a1e',
    messagingSenderId: '114708249147',
    projectId: 'beebuzz-dda69',
    storageBucket: 'beebuzz-dda69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPY4JuC_ofgVL6rcqntugMrUNzL_r_LE',
    appId: '1:114708249147:ios:d377469f5d417a1bfa3a1e',
    messagingSenderId: '114708249147',
    projectId: 'beebuzz-dda69',
    storageBucket: 'beebuzz-dda69.appspot.com',
    iosBundleId: 'com.alphadevelopmentco.BeeBuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPY4JuC_ofgVL6rcqntugMrUNzL_r_LE',
    appId: '1:114708249147:ios:691ab2e02e469f74fa3a1e',
    messagingSenderId: '114708249147',
    projectId: 'beebuzz-dda69',
    storageBucket: 'beebuzz-dda69.appspot.com',
    iosBundleId: 'com.example.beebuzz.RunnerTests',
  );
}
